/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin GitHub OAuth sign-in
         * @description Documented for completeness — this is a browser redirect, not a JSON API,
         *     and stays hand-wired on chi. Sets an `oauth_state` cookie (HttpOnly,
         *     SameSite=Lax, 10 min) and redirects to GitHub with scopes
         *     `read:user`, `user:email`.
         */
        get: operations["githubLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GitHub OAuth callback
         * @description Documented for completeness — browser redirect, hand-wired on chi.
         *     Validates `state` against the `oauth_state` cookie, exchanges `code`,
         *     then redirects to `{FRONTEND_URL}/auth/callback?token=<jwt>`.
         */
        get: operations["githubCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a device-flow pairing
         * @description Called by the agent CLI. Takes no request body.
         */
        post: operations["deviceAuthorize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Poll for the agent token
         * @description Polled by the agent CLI at the `interval` returned by
         *     `deviceAuthorize` (5s). Returns 202 while the user has not yet approved.
         */
        post: operations["deviceToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a pending device code
         * @description Called by the front's `/device?code=XXXX-XXXX` page. Creates a `pending`
         *     agent plus its agent token.
         */
        post: operations["deviceApprove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List agents
         * @description Org-scoped, ordered `created_at DESC`. No pagination or filters.
         */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentID"];
            };
            cookie?: never;
        };
        /** Get an agent */
        get: operations["getAgent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List agent tokens
         * @description Org-scoped, non-revoked only, ordered `created_at DESC`. The token hash
         *     never leaves the hub.
         */
        get: operations["listAgentTokens"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-tokens/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TokenID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke an agent token */
        post: operations["revokeAgentToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List jobs
         * @description Org-scoped, ordered `created_at DESC`. No pagination or filters.
         */
        get: operations["listJobs"];
        put?: never;
        /**
         * Dispatch a job to an agent
         * @description Creates the job in state `accepted` and pushes it to the agent over the
         *     gRPC stream. No `job.status` event is emitted for the creation itself —
         *     the client learns the job exists from this response.
         */
        post: operations["dispatchJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        /** Get a job */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a job
         * @description Asks the agent to stop the job. The response body is the job **as it was
         *     before cancellation** — the agent drives `stopping → cancelled`
         *     asynchronously and the client observes it over `job.status` events.
         */
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        /**
         * Get a job's logs
         * @description The complete log, ordered `sequence ASC`. There is no `since`, `limit`,
         *     `tail` or `follow` — the front seeds a buffer from this snapshot and
         *     appends live lines from `job.log` WS events.
         */
        get: operations["getJobLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live event stream (WebSocket upgrade)
         * @description Not a REST operation — documented so this file is a complete picture of
         *     the boundary. Frames are JSON `HubEvent` values (see
         *     `components/schemas/HubEvent`); the connection is server-push only,
         *     client frames are read and discarded.
         *
         *     Auth is the JWT in the `token` query param (browsers cannot set headers
         *     on a WS handshake); an `Authorization: Bearer` header also works for
         *     proxied connections. Events are fanned out per-org at subscription time.
         *
         *     The hub pings every 30s and expects the connection to stay within a 60s
         *     read deadline. The per-subscriber buffer is 64 events with a
         *     non-blocking send: **a slow consumer silently drops events**, so the
         *     client must treat the stream as best-effort and reconcile via REST.
         */
        get: operations["eventStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The single error shape used by every non-2xx JSON response. */
        Error: {
            error: string;
        };
        /** @enum {string} */
        AgentStatus: "online" | "offline";
        /**
         * @description `unspecified` is reachable when an agent reports a status the hub cannot
         *     map; it is not a state a healthy job passes through.
         * @enum {string}
         */
        JobState: "unspecified" | "accepted" | "pulling_image" | "creating_container" | "starting_container" | "running" | "stopping" | "cancelled" | "succeeded" | "failed" | "timed_out";
        /** @enum {string} */
        LogStream: "unspecified" | "stdout" | "stderr";
        /** @enum {string} */
        PullPolicy: "unspecified" | "always" | "if_not_present" | "never";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            avatar_url: string;
            /**
             * Format: uuid
             * @description Taken from the JWT claim, not the user record.
             */
            org_id: string;
        };
        Agent: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            version: string;
            hostname: string;
            status: components["schemas"]["AgentStatus"];
            /** Format: date-time */
            last_seen_at?: string;
            /** Format: date-time */
            created_at: string;
            /**
             * Format: float
             * @description Latest heartbeat snapshot. Absent until the agent first reports.
             */
            cpu_usage_percent?: number;
            /** Format: int64 */
            memory_used_bytes?: number;
            /** Format: int64 */
            memory_total_bytes?: number;
            /** Format: int64 */
            disk_used_bytes?: number;
            /** Format: int64 */
            disk_total_bytes?: number;
            /** Format: int32 */
            running_containers?: number;
        };
        AgentToken: {
            /** Format: uuid */
            id: string;
            name: string;
            /**
             * Format: uuid
             * @description Set once the token is bound to a paired agent.
             */
            agent_id?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_used_at?: string;
        };
        VolumeMount: {
            host_path: string;
            container_path: string;
            read_only: boolean;
        };
        ResourceLimits: {
            /** Format: int64 */
            memory_bytes: number;
            /** Format: float */
            cpu_cores: number;
        };
        /**
         * @description What to run in Docker. `image` is the only required — and the only
         *     validated — field.
         *
         *     Optional scalars carry `x-go-type-skip-optional-pointer` so the
         *     generated Go struct mirrors `domain.JobSpec` field for field, keeping
         *     the transport ↔ domain mapper mechanical.
         */
        JobSpec: {
            image: string;
            command?: string[];
            args?: string[];
            env?: {
                [key: string]: string;
            };
            volume_mounts?: components["schemas"]["VolumeMount"][];
            resource_limits?: components["schemas"]["ResourceLimits"];
            working_dir?: string;
            network_mode?: string;
            labels?: {
                [key: string]: string;
            };
            pull_policy?: components["schemas"]["PullPolicy"];
            privileged?: boolean;
            /** Format: int32 */
            timeout_seconds?: number;
        };
        Job: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            agent_id: string;
            state: components["schemas"]["JobState"];
            spec: components["schemas"]["JobSpec"];
            message: string;
            /** Format: int32 */
            exit_code?: number;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string;
            /** Format: date-time */
            created_at: string;
        };
        JobLog: {
            /**
             * Format: int64
             * @description Autoincrement row id — the only non-UUID identifier in this API.
             */
            id: number;
            line: string;
            stream: components["schemas"]["LogStream"];
            /**
             * Format: int64
             * @description Per-job ordering key, assigned by the agent.
             */
            sequence: number;
            /** Format: date-time */
            timestamp: string;
        };
        DispatchJobRequest: {
            /** Format: uuid */
            agent_id: string;
            spec: components["schemas"]["JobSpec"];
        };
        DeviceAuthorizeResponse: {
            /** @description 32 lowercase hex chars. Polled by the agent CLI. */
            device_code: string;
            /**
             * @description `XXXX-XXXX` from the ambiguity-free alphabet
             *     `ABCDEFGHJKLMNPQRSTUVWXYZ23456789`. Typed by the human.
             */
            user_code: string;
            /** @description `{FRONTEND_URL}/device?code={user_code}` */
            verification_uri: string;
            /** @description Seconds until the device code expires (TTL is 10 minutes). */
            expires_in: number;
            /** @description Seconds the agent should wait between polls. */
            interval: number;
            /** @description Where the paired agent should open its gRPC stream. */
            grpc_addr: string;
        };
        DeviceTokenRequest: {
            device_code: string;
        };
        DeviceTokenResponse: {
            /**
             * @description Opaque agent token (base64url, 32 random bytes) — **not** a JWT.
             *     Presented as gRPC metadata by the agent.
             */
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
        };
        DeviceApproveRequest: {
            user_code: string;
        };
        JobStatusPayload: {
            state: components["schemas"]["JobState"];
            message?: string;
            /** Format: int32 */
            exit_code?: number;
        };
        LogLine: {
            line: string;
            stream: components["schemas"]["LogStream"];
            /** Format: int64 */
            sequence: number;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description One event per job per flush batch, never one per line. */
        JobLogPayload: {
            lines: components["schemas"]["LogLine"][];
        };
        /**
         * @description Agent lifecycle and liveness. Carries no `payload` — heartbeat metrics
         *     are persisted on the agent record, not pushed, so a client wanting fresh
         *     metrics refetches `/api/v1/agents`.
         *
         *     For `agent.heartbeat`, `at` is the **agent-supplied** timestamp; for the
         *     other two it is hub time.
         */
        AgentEvent: {
            /** @enum {string} */
            type: "agent.connected" | "agent.disconnected" | "agent.heartbeat";
            /** Format: uuid */
            agent_id: string;
            /** Format: date-time */
            at: string;
        };
        /**
         * @description Emitted only when a guarded state transition actually applied, so
         *     duplicates are already suppressed hub-side.
         */
        JobStatusEvent: {
            /** @enum {string} */
            type: "job.status";
            /** Format: uuid */
            agent_id: string;
            /** Format: uuid */
            job_id: string;
            /** Format: date-time */
            at: string;
            payload: components["schemas"]["JobStatusPayload"];
        };
        /** @description Emitted after the log batch is durably written. */
        JobLogEvent: {
            /** @enum {string} */
            type: "job.log";
            /** Format: uuid */
            agent_id: string;
            /** Format: uuid */
            job_id: string;
            /** Format: date-time */
            at: string;
            payload: components["schemas"]["JobLogPayload"];
        };
        /** @description A single frame on the `/ws` stream. */
        HubEvent: components["schemas"]["AgentEvent"] | components["schemas"]["JobStatusEvent"] | components["schemas"]["JobLogEvent"];
    };
    responses: {
        /** @description Missing or invalid bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description No such resource in the caller's org. Cross-tenant access is reported as
         *     404, never 403 — this API has no 403.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Malformed or invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Per-IP token bucket on the public routes (0.5/s refill, burst 10). */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server-side failure. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        AgentID: string;
        JobID: string;
        TokenID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    githubLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Temporary redirect to GitHub's authorize URL. */
            307: {
                headers: {
                    Location?: string;
                    /** @description `oauth_state=<hex>; Path=/; Max-Age=600; HttpOnly; SameSite=Lax` */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    githubCallback: {
        parameters: {
            query: {
                state: string;
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Temporary redirect to the front-end callback route carrying the JWT. */
            307: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /**
             * @description Missing/invalid token, **or** the user record no longer exists —
             *     the hub deliberately answers 401 rather than 404 for the latter.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    deviceAuthorize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device and user codes, plus where to poll and approve. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceAuthorizeResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    deviceToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceTokenRequest"];
            };
        };
        responses: {
            /**
             * @description Approved. `access_token` is an **opaque agent token** (base64url,
             *     32 random bytes) used as gRPC metadata — not a JWT.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceTokenResponse"];
                };
            };
            /**
             * @description Still pending approval; keep polling. Body is
             *     `{"error": "authorization_pending"}`.
             *
             *     Note: the hub writes this branch without setting `Content-Type`, so
             *     the response is sniffed as `text/plain` on the wire. Documented as
             *     JSON because that is what the body actually contains.
             */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Missing or undecodable `device_code`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Device code expired or unknown (the hub does not distinguish). */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    deviceApprove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceApproveRequest"];
            };
        };
        responses: {
            /** @description Approved. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Missing `user_code`, or the service rejected it — the error text is
             *     the service's own (`device code expired`, `already approved`,
             *     `record not found`).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All agents in the caller's org. Empty list serializes as `[]`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The agent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listAgentTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active agent tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentToken"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    revokeAgentToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TokenID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /**
             * @description Unknown token, already revoked, or belonging to another org — all
             *     three answer 404.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All jobs in the caller's org. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    dispatchJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DispatchJobRequest"];
            };
        };
        responses: {
            /** @description The created job. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Undecodable body, missing `agent_id`, or missing `spec.image`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The agent exists but has no live gRPC stream. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
            /**
             * @description The agent disconnected between the liveness check and the send. The
             *     job row is transitioned to `failed`.
             */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation requested; job state is still the pre-cancel state. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The job already reached a terminal state, or the agent is not connected. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getJobLogs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every log line recorded for the job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobLog"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    eventStream: {
        parameters: {
            query: {
                /** @description The session JWT. */
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols — the WebSocket is established. */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Missing or invalid token. Unlike every other endpoint, this one
             *     answers `text/plain` (`unauthorized\n`), not the JSON error shape.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
