[build]
  cmd        = "go build -o ./tmp/hub ./cmd/hub"
  entrypoint = "./tmp/hub"
  delay      = 500
  exclude_dir = ["tmp", "dist", "migrations"]
  include_ext = ["go"]
  kill_delay  = "1s"

[log]
  main_only = true
